-- Admin / Manager role schema (MVP)
-- Run in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- 1) Role dictionary
create table if not exists public.roles (
  id smallint generated by default as identity primary key,
  code text not null unique check (code in ('user', 'manager', 'admin')),
  name_ko text not null,
  priority smallint not null check (priority >= 0),
  created_at timestamptz not null default now()
);

insert into public.roles (code, name_ko, priority)
values
  ('user', '일반 사용자', 10),
  ('manager', '매니저', 50),
  ('admin', '관리자', 100)
on conflict (code) do update
set name_ko = excluded.name_ko,
    priority = excluded.priority;

-- 2) User role assignment history
create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id smallint not null references public.roles(id),
  granted_by uuid null references auth.users(id) on delete set null,
  granted_reason text null,
  granted_at timestamptz not null default now(),
  revoked_at timestamptz null
);

create index if not exists user_roles_user_active_idx
  on public.user_roles (user_id, revoked_at, granted_at desc);

create index if not exists user_roles_role_active_idx
  on public.user_roles (role_id, revoked_at, granted_at desc);

-- At most one active role per user (history rows with revoked_at are allowed).
create unique index if not exists user_roles_one_active_role_per_user
  on public.user_roles (user_id)
  where revoked_at is null;

-- 3) Moderator/Admin action logs
create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid null references auth.users(id) on delete set null,
  target_user_id uuid null references auth.users(id) on delete set null,
  action text not null,
  resource_type text not null,
  resource_id text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_actor_created_idx
  on public.admin_audit_logs (actor_user_id, created_at desc);

create index if not exists admin_audit_logs_target_created_idx
  on public.admin_audit_logs (target_user_id, created_at desc);

create index if not exists admin_audit_logs_resource_idx
  on public.admin_audit_logs (resource_type, resource_id, created_at desc);
